---
<a id='8-ejercicio'></a>

Alumna: Castillo Dorantes Sandra Geraldine
## Sesion 1 - Ejercicio de Cierre ✏️

**Contexto:** Trabajas en el área de estadística de una aseguradora de autos.
Tu jefe te entregó la siguiente mini-cartera y quiere que le entregues
un resumen ejecutivo antes de la siguiente reunión.

### Datos

In [1]:
# ── Cartera de autos — carga estos datos ────────────────────────────────────
import pandas as pd

cartera_autos = {
    "poliza":     ["A-101","A-102","A-103","A-104","A-105","A-106","A-107","A-108","A-109","A-110"],
    "asegurado":  ["Sofía R.","Miguel T.","Laura G.","Roberto M.","Carmen P.",
                   "Andrés F.","Lucía H.","Diego V.","Patricia N.","Héctor S."],
    "edad":       [24, 38, 31, 55, 42, 27, 46, 33, 58, 22],
    "vehiculo":   ["Sedán","SUV","Hatchback","SUV","Sedán",
                   "Pick-up","Sedán","Hatchback","SUV","Sedán"],
    "modelo_year":[2022, 2023, 2020, 2024, 2021, 2023, 2019, 2022, 2024, 2023],
    "prima_anual":[3_200, 5_800, 2_900, 7_200, 4_100,
                   6_500, 3_800, 2_750, 8_100, 2_600],
    "deducible":  [5_000, 8_000, 5_000, 10_000, 5_000,
                   8_000, 5_000, 5_000, 10_000, 5_000],
    "siniestros": [0, 1, 0, 0, 2, 1, 0, 0, 1, 0],
    "costo_siniestros": [0, 18_500, 0, 0, 42_000, 11_200, 0, 0, 28_000, 0],
}

df_autos = pd.DataFrame(cartera_autos)
print(f"Cartera cargada: {len(df_autos)} pólizas")
df_autos

Cartera cargada: 10 pólizas

,poliza,asegurado,edad,vehiculo,modelo_year,prima_anual,deducible,siniestros,costo_siniestros
0,A-101,Sofía R.,24,Sedán,2022,3200,5000,0,0
1,A-102,Miguel T.,38,SUV,2023,5800,8000,1,18500
2,A-103,Laura G.,31,Hatchback,2020,2900,5000,0,0
3,A-104,Roberto M.,55,SUV,2024,7200,10000,0,0
4,A-105,Carmen P.,42,Sedán,2021,4100,5000,2,42000
5,A-106,Andrés F.,27,Pick-up,2023,6500,8000,1,11200
6,A-107,Lucía H.,46,Sedán,2019,3800,5000,0,0
7,A-108,Diego V.,33,Hatchback,2022,2750,5000,0,0
8,A-109,Patricia N.,58,SUV,2024,8100,10000,1,28000
9,A-110,Héctor S.,22,Sedán,2023,2600,5000,0,0

In [23]:
# ── Tarea 1: Estadísticas descriptivas ──────────────────────────────────────
# Escribe tu solución aquí
print("----ESTADISTICAS DESCRIPTIVAS----")
df_autos.describe().round(2)

----ESTADISTICAS DESCRIPTIVAS----

,edad,modelo_year,prima_anual,deducible,siniestros,costo_siniestros,frecuencia_ind
count,10.00,10.00,10.00,10.00,10.00,10.0,10.00
mean,37.60,2022.10,4695.00,6600.00,0.50,9970.0,0.40
std,12.54,1.66,2031.21,2170.51,0.71,14987.7,0.52
min,22.00,2019.00,2600.00,5000.00,0.00,0.0,0.00
25%,28.00,2021.25,2975.00,5000.00,0.00,0.0,0.00
50%,35.50,2022.50,3950.00,5000.00,0.00,0.0,0.00
75%,45.00,2023.00,6325.00,8000.00,1.00,16675.0,1.00
max,58.00,2024.00,8100.00,10000.00,2.00,42000.0,1.00

In [3]:
# ── Tarea 2: Resumen ejecutivo ───────────────────────────────────────────────
# Escribe tu solución aquí

print(" --------RESUMEN EJECUTIVO--------")
print(f"Total de polizas: {len(df_autos)}")
print(f"Edad promedio: {int(sum(df_autos['edad'])/len(df_autos))}")
print(f"Prima anual total: {sum(df_autos['prima_anual']):,}")
print(f"Prima maxima: {df_autos['prima_anual'].max():,}")
print(f"Prima minima: {df_autos['prima_anual'].min():,}")
print(f"Deducible promedio: {sum(df_autos['deducible']/len(df_autos)):,}")
print(f"Deducible maximo: {df_autos['deducible'].max():,}")
print(f"Deducible minimo: {df_autos['deducible'].min():,}")
print(f"Siniestros totales: {sum(df_autos['siniestros'])}")
print(f"Siniestro maximo: {df_autos['siniestros'].max():,}")
print(f"Siniestro minimo: {df_autos['siniestros'].min():,}")
print(f"Costo total de siniestros: {sum(df_autos['costo_siniestros']):,}")
print(f"Costo primedio por siniestro: {sum(df_autos['costo_siniestros'])/len(df_autos):,}")

 --------RESUMEN EJECUTIVO--------
Total de polizas: 10
Edad promedio: 37
Prima anual total: 46,950
Prima maxima: 8,100
Prima minima: 2,600
Deducible promedio: 6,600.0
Deducible maximo: 10,000
Deducible minimo: 5,000
Siniestros totales: 5
Siniestro maximo: 2
Siniestro minimo: 0
Costo total de siniestros: 99,700
Costo primedio por siniestro: 9,970.0

In [4]:
# ── Tarea 3: Filtrar pólizas con siniestros ─────────────────────────────────
# Escribe tu solución aquí
print("-----POLIZAS CON SINIESTROS-------")
df_autos[df_autos['siniestros']>0]

-----POLIZAS CON SINIESTROS-------

,poliza,asegurado,edad,vehiculo,modelo_year,prima_anual,deducible,siniestros,costo_siniestros
1,A-102,Miguel T.,38,SUV,2023,5800,8000,1,18500
4,A-105,Carmen P.,42,Sedán,2021,4100,5000,2,42000
5,A-106,Andrés F.,27,Pick-up,2023,6500,8000,1,11200
8,A-109,Patricia N.,58,SUV,2024,8100,10000,1,28000

In [ ]:
# ── Tarea 4: Columna frecuencia_individual ───────────────────────────────────
# Escribe tu solución aquí

print("----COLUMNA FRECUENCIA INDIVIDUAL----")
df_autos['frecuencia_ind'] = (df_autos['siniestros'] > 0).replace({True: 1, False: 0})
df_autos[['poliza', 'siniestros', 'frecuencia_ind']]

----COLUMNA FRECUENCIA INDIVIDUAL----

C:\Users\HP\AppData\Local\Temp\ipykernel_14232\3699323972.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_autos['frecuencia_ind'] = (df_autos['siniestros'] > 0).replace({True: 1, False: 0})

  poliza  siniestros  frecuencia_ind
0  A-101           0               0
1  A-102           1               1
2  A-103           0               0
3  A-104           0               0
4  A-105           2               1
5  A-106           1               1
6  A-107           0               0
7  A-108           0               0
8  A-109           1               1
9  A-110           0               0

In [22]:
# ── Tarea 5 Bonus: Prima promedio por tipo de vehículo ──────────────────────
# Escribe tu solución aquí
print("----PRIMA PROMEDIO POR VEHICULO----")
grupo = df_autos.groupby(df_autos['vehiculo'])
modelos = grupo['prima_anual'].mean()

modelos

----PRIMA PROMEDIO POR VEHICULO----

vehiculo
Hatchback    2825.000000
Pick-up      6500.000000
SUV          7033.333333
Sedán        3425.000000
Name: prima_anual, dtype: float64